parameters:
    do.class.factory: DigitalOceanV2\DigitalOceanV2
    do.class.adapter: DigitalOceanV2\Adapter\GuzzleAdapter

services:
#    bizbink_do_dyn_dns.example:
#        class: bizbink\DODynDNSBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    do.adapter:
        class: %do.class.adapter%
        public: false
        arguments: [%do_secret%]

    do.factory:
        class: %do.class.factory%
        arguments: [@do.adapter]
